# Site settings

url: "http://dmontesdeocaz.github.io"
title: "{ David Montes de Oca Zapiain }"
description: "Blog and website of David Montes de Oca Zapiain."
keywords: "Material Informatics, Multi-scale modelling, MKS"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-35880426-3"
disqus-shortname: "dmontesdeocaz"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/writeright.jpg"
    date: "August 2015 - Today"
    description: " Joined @ <a href=\"http://http://mined.gatech.edu/members\">MINED Research Group</a> with Dr. Kalidindi at the Georgia Institute of Technology"
  - image: "/img/career/pwnmail.jpg"
    date: "January 2015 - July 2015"
    description: " Started Master's Degree in Georgia Tech Lorraine"
  - image: "/img/career/uoa.jpg"
    date: "August 2011 - December 2014"
    description: "Bachelor studies @ <a href=\"http://me.gatech.edu\" target=\"_blank\"> Georgia Institute of Tecnology</a> on Mechanical Engineering"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/dmontesdeocaz"
  - title: "linkedin"
    url: "https://www.linkedin.com/pub/david-montes-de-oca-zapiain/57/776/911"


404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
